### ISSUE TITLE
Corner Calibration: Show warning if user tries to start engraving without homing  cycle

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#1013]
If the device is not homed, it's possible to click the "Engrave calibration markers" button in the user corner calibration page. Of course it fails but it does not tell the user why or how to solve the issue. There should be a warning telling the user that he needs to to a homing cycle first.

**Comment by hungerpirat** [comment]
I'd suggest to just do the homing cycle automatically instead requesting
additional steps from the user.

**Comment by Gallore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Corner calibration: Show warning if user tries to start engraving without homing cycle](https://trello.com/c/gk00BDkO/655-corner-calibration-show-warning-if-user-tries-to-start-engraving-without-homing-cycle)
