### ISSUE TITLE
Implement unproportional scaling of user graphics in the working area.

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#109]
It should be possible to do a unproportional scaling of graphics on the working area. However, this should not be the default action. 

We need a usability concept for this one: We could do the unproportional scaling while the user presses a modifier key (eg: strg). But this would be in contrast to most graphic editors were you need to press the modifier to HAVE the proportional scaling.

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mirrorring + Proportional scaling](https://trello.com/c/b8AFPcG3/682-mirrorring-proportional-scaling)

**Comment by hungerpirat** [comment]
Nice one. Reported 2017 -> fixed recently, already released. @Gallore
