### ISSUE TITLE
NPS: Add more data to user review [/1]

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#1137]
When we submit a user review ("Would you recommend Mr Beam to your friends? 1-10?") we need to add more device data and also ask the user more details.

Device data:
- SW version (mr beam plugin)
- model (MRBEAM2_DC, ...)
- production date (be aware that older devices do not have a model_id or production date)

Server side:
We need to add the date when the review was uploaded (which might be very different from the date when the review was done.) The creation date of the json file in the GCP bucket could be used. All following components need to user or forward this date.

User data:
- We should ask the user if it's ok to contact her/him "in case we have questions" and offer to add email address or phone number. Could be one (free text) field or two fields. We could also pre-fill the user's email address, but I lean towards not doing this. We probably also need a statement what we use these data for. 
- the user should have the option to change it's rating. Since we asks in any case for feedback and contact details, it does not change the logic/flow of the user review screen.
- please remove the "wow thank you" text as if we were surprised about a good rating. Let's have a neutral "Thank you for your feedback" or "Your feedback is super important to us" or so.
- (Optional) If the user gave us a good rating, we could add another screen AFTER he submitted his complete feedback. This new screen would be dedicated to suggest that the suer rates us on rating pages. this page should get a visual makeover I think. In my mind we should show there logos of well known rating platforms. But I need to check with Jessie. I see this screen as optional, we can add it later on as well.
  - Our Shop (as it is currently, but please let's use a redirect `mr-beam.org/beamos/review`) 
  - Google
  - Trustpilot

**Comment by Gallore** [comment]
Device data and server side fixed in commit 915d4d8

**Comment by Gallore** [comment]
@khaledsherkawi please focus un the part "User data" in the description. The other things are already done.

**Comment by Gallore** [comment]
@khaledsherkawi Please KEEP the switch for users who rated 7 and better!
We need a switch AFTER the suer entered his feedback and submitted it:
- <7 "Thank you for your feedback"
- >= 7: "Thank you for your feedback" + Please give us a review. For now this screen could be simple - just what we have now. Bonus points if the call to action (the review link) is a bit more visible. Later on (probably not for this release) we redesignt this scree according to how I described it in the description.

**Comment by Gallore** [comment]
Wording:

 **Screen 1**

Title: 
`How likely are you to recommend Mr Beam to a friend or colleague?`
Please add the text "Not at all likely" to the 1 button and "Extremely likely" to the 10 button. Ideally on top or left/right. Should not be too big.

**Screen 2**

Title:
`Thank you for your response.`

Label Feedback field: 
`Help us by explaining your score...`

Label contact field: 
`Phone or email: (optional)`
I think the word "optional" should be as bold as the "Phone or email" is

Contact information field explanation:
`If it's ok to contact you about your feedback.`
muted - could be within the same line as the label - with this one I'm not 100% sure.

Button: 
`Send`

I took my ideas from there:
https://www.wootric.com/blog/what-is-nps-the-concept-and-formula/

**Screen 3 - positive**

Title: 
`Thank you for your feedback.`

Then:
```
Positive reviews from awesome customers like you help others to feel confident about choosing Mr Beam too. 
Could you take 60 seconds to go to the [Link: Mr Beam Store] and share your happy experiences?

We will be forever grateful. Thank you in advance for helping us out!
Your Mr Beam team
```


 
**Screen 3 - negative**

Title: 
`Thank you for your feedback.`

Then:
```
Did you know:
We have a great online support portal with lots of helpful articles to help out with common problems. There you can also find tips on what materials to use or how to create designs and more. And of course you can reach our friendly support team at any time by writing us a ticket.
[Link: Go to the Mr Beam Support Portal]

Your Mr Beam team
```

**Comment by khaledsherkawi** [comment]
@Gallore 
The only thing I kept from before is the back button between screens 1 and 2. The rating bar doesn't look good on top of screen 2. In addition the CSS of the rating bar (on top of screen 2) will be confusing to the user. If we leave it without the their decision highlighted they will think that they have to vote again and if we highlight their decision they will think they cannot change it. With the back button they can choose to go back and answer differently. 

Screen 1:
![Screen 1](https://user-images.githubusercontent.com/54568489/107754613-067b6d80-6d22-11eb-9420-ea5505b8be8a.PNG)

Screen 2:
![Screen 2](https://user-images.githubusercontent.com/54568489/107754618-08453100-6d22-11eb-9a2d-61067fe31233.PNG)

Screen 3 - positive review:
![Screen 3 - Negative Review](https://user-images.githubusercontent.com/54568489/107754624-0a0ef480-6d22-11eb-9a03-47425e562269.PNG)

Screen 4 - negative review:
![Screen 3 - Positive Review](https://user-images.githubusercontent.com/54568489/107754629-0bd8b800-6d22-11eb-9b9c-4a5ffd3ec4df.PNG)
