### ISSUE TITLE
Mr Beam should not mess up sorting of uploaded files due to timereset

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#114]
If the device doesn't have internet access, it can not sync it's clock and therefore it assumes a time in the past (2016 I assume). The thing is that with every reboot of the device  its time (re)sets at the same starting point. This messes up the sorting of uploaded files.

**Comment by make-ing** [comment]
there is a package called fake-hwclock which saves the date on shutdown and sets it on start (/etc/fake-hwclock.data)

```fake-hwclock save``` <-- to manualy save the current time to the data file
```fake-hwclock load``` <-- to manualy load the time stored in the data file
