### ISSUE TITLE
Bug report: Invalid Gcode ID:24

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#116]
on device 832F.
Device lasered about halb of the job before this error happened.

Log, Gcode, temp.svg and original SVG attached.

[Incalid Gcode 24.zip](https://github.com/mrbeam/MrBeamPlugin/files/1135544/Incalid.Gcode.24.zip)

**Comment by make-ing** [comment]
I tested the gcode and it worked fine. It seems that this is a random communication bug/error. Further testing needed but its not about the actual gcode or svg file.
