### ISSUE TITLE
Make visible in Left menu which part of the SVG is selected in workspace

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#1166]
Use Case: I have an SVG with lots of shapes in it so I use the split, then I am selecting one in the work area, and then I want to know which one it is. The other way around works with making the stroke a bit thicker, so when hovering over the different parts in the left menu. 

<img width="1426" alt="Bildschirmfoto 2021-02-17 um 22 39 04" src="https://user-images.githubusercontent.com/7208102/108272307-58812080-7172-11eb-95dd-04b8e2f79710.png">

**Comment by clemniem** [comment]
I think this might be doable with some light background color changing, like it is often done in menus on hover. Probably a good story also for newbies or rusted frontend devs like me :P

**Comment by hungerpirat** [comment]
already fixed in beta.
Thanks for reporting @clemniem
