### ISSUE TITLE
Make "experimental_beta_feature"s available for support user.

### ISSUE THREAD

**Issue by amrsoll** [mrbeam/MrBeamPlugin#1189]
This can allow to perform Lens Calibration without changing software version. This can be done using the `env_support_mode` boolean, adding a `.support_mode` css class to the `<body>` and add the `.support_mode .experimental_beta_feature {}` rule to the css file.

See 
`mrbeam_initscript.jinja2`
```js
    var MRBEAM_ENV_SUPPORT_MODE = {{ 'true' if env_support_mode else 'false' }};
    var MRBEAM_LANGUAGE = "{{ language }}";
    var MRBEAM_SW_TIER = "{{ software_tier }}";
```

**Comment by Gallore** [comment]
I pushed to accidentally `develop`
