### ISSUE TITLE
Display errors in laser params screen and quick form form [1] 

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#1279]
Reproducible: 
- in current Stable (0.9.2) and Beta (0.9.6)
- Chrome (91.0.4472.101) and FireFox and Safari
- MacOS 11.4
(please add if reproducible or not in other environments.)

Laser Params (with advanced settings)
- 4 digit numbers in the input fields are not fully visible
- Headlines Speed range and engraving time optimisation are displaced
<img width="705" alt="Screenshot 2021-06-18 at 16 02 58" src="https://user-images.githubusercontent.com/4582388/122574723-3f20b000-d050-11eb-8e91-542dad62a50f.png">

Quick form form:
<img width="571" alt="Screenshot 2021-06-18 at 15 58 37" src="https://user-images.githubusercontent.com/4582388/122574728-41830a00-d050-11eb-8231-f8d3f63065ca.png">

**Comment by khaledsherkawi** [comment]
moved to JIRA
