### ISSUE TITLE
Gray Outlines in Frontend get bigger than design

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#129]
If a design is made smaller (a lot smaller), at some point the gray outlines start to look funny and not right.

**Comment by hungerpirat** [comment]
@clemniem are the grey outlines part of the design? or are you talking about the transformation bounding  boxes? 
Please provide a screenshot.

**Comment by clemniem** [comment]
Yes, its the grey bounding box. See the large Mr Beam Logo on 2747 or 832F.
<img width="454" alt="screen shot 2017-07-25 at 19 13 28" src="https://user-images.githubusercontent.com/7208102/28584543-65e0f984-716d-11e7-8154-7f8f17ff2ca9.png">

**Comment by Gallore** [comment]
@clemniem : Is this still reproducible? Is assume it's fixed now. Please test and close if so. thx

**Comment by clemniem** [comment]
It is still reproducible. Just take any large design and make it very small.
