### ISSUE TITLE
anodized aluminum settings 

### ISSUE THREAD

**Issue by MrBeamDaniel** [mrbeam/MrBeamPlugin#139]
engraving just the outline of a PNG file on anodized aluminum instead of everything.

![img_5522](https://user-images.githubusercontent.com/30661088/29575691-9516773e-8765-11e7-9cf7-b2ddfc50268d.JPG)
![unbenannt-2](https://user-images.githubusercontent.com/30661088/29575689-951433f2-8765-11e7-9ce2-9647d3120829.png)

**Comment by clemniem** [comment]
fixed.
