### ISSUE TITLE
quicktext/gcode name error

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#143]
If you try to engrave just a dot, the filename is '..gco' and then throws an exception, because the text engraved is the filename, this should not be the case.

**Comment by clemniem** [comment]
What should happen in: convert.js line 456 _sanitize(name).

**Comment by hungerpirat** [comment]
My assumption: The gcode filename is generated automatically based on the
origin filenames of the placed desigs. E.g. foo.svg => foo.gco , foo.svg +
bar.svg + bam.svg => foo_and_3more.gco
When using the quicktext-feature, there is no real filename anymore, it
uses the content as a placeholder.
the _sanitize should ensure that the generated filename is a valid
filename. This probably fails if the input is just '.'

**Comment by clemniem** [comment]
yes, that is the problem. The question was more like: what kind of names should be allowed, and what to do with an invalid one?

**Comment by hungerpirat** [comment]
If the name is invalid, I would suggest to generate a name with a
timestamp.

**Comment by clemniem** [comment]
if an invalid filename is found, it will prepend 'mb' and append a timestamp to the .gco filename.
