### ISSUE TITLE
laserhead should be moved to centre after calibration

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#145]
During the camera calibration the user needs to go back to working area and move the laserhead to the middle so he can see the NE corner, this should maybe be done automatically?

**Comment by clemniem** [comment]
maybe it isnt necessary on mr beam 56D4 it works out by 5-10mm or so.
Please check on other machines.

**Comment by Gallore** [comment]
Self Check: move head to center after corners are lasered.
User mode: no action required.

**Comment by Gallore** [comment]
self_check: done
