### ISSUE TITLE
Photo button (take picture) doesnt work

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#146]
the photo button on front page: upload/text/**photo**
No pop up asking me for permissions either. Is this a settings thing?

**Comment by hungerpirat** [comment]
maybe we should update the js library. Checkout
https://github.com/mrbeam/MrBeamPlugin/blob/master/octoprint_mrbeam/static/js/lib/photobooth_min.js

**Comment by clemniem** [comment]
I think we are using the latest version, but it is never called. 

There could be some issue with https and modern chrome browsers. But can't really test it right now.

Is there any logic in the jinja file thats loaded? 
https://github.com/mrbeam/MrBeamPlugin/blob/master/octoprint_mrbeam/templates/take_photo.jinja2

Does it work on someones computer?

**Comment by Gallore** [comment]
See also #105
