### ISSUE TITLE
after shutdown sometimes leds stay on

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#148]
sometimes all leds go dark
sometimes only the ones inside stay on in white
sometimes the ones on the side stay red as well
--> this is quite confusing, because I am not sure if it is still shutting down or not

**Comment by Gallore** [comment]
Once the device can be turned off, it should signal that. Let's have only the middle or bottom LEDs red on all sites once the user can turn it off. 
I assume this should be implemented in the LED daemon.
