### ISSUE TITLE
laser settings stay visible even after deleting design file

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#150]
<img width="1087" alt="screen shot 2017-09-27 at 19 20 41" src="https://user-images.githubusercontent.com/7208102/30928483-10bff276-a3bc-11e7-9ea2-799df3863d72.png">

How to reproduce:
- take design file with two colors
- laser it
- remove design
- place design with only engraving (eg photo)
- press laser 
---> the settings below appear, even though there is no laser design placed

**Comment by Gallore** [comment]
Teja to investigate
