### ISSUE TITLE
air extracter stays on even after shutdown

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#151]
after pressing shutdown (long press for 5 seconds) the air extracter is still running.

**Comment by Gallore** [comment]
Solve in our plugin or in iobeam ?
Teja: for safety send the grlb as stop as well.

**Comment by make-ing** [comment]
grbl safety stop should be handled somewhere else. iobeam is not the right place, maybe in the button handler which initiates the shutdown.

**Comment by make-ing** [comment]
fixed in the develop branch of iobeam by listening to the SIGTERM signal and turing off the fan in this case.
