### ISSUE TITLE
marker calibration: no back button on last corner (NE)

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#153]
After clicking once, you cannot take it back or get back to old corners etc. see screenshot after clicking once on NE

<img width="644" alt="screen shot 2017-09-28 at 10 47 27" src="https://user-images.githubusercontent.com/7208102/30957421-789261b2-a43a-11e7-89f2-d6f4adfa9e59.png">

**Comment by hungerpirat** [comment]
fixed with b5bbdb5b7f6846ccce8c24fd9ce08ce8ed9b4cae
