### ISSUE TITLE
workingArea, wrong size at first load

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#157]
sometimes the working area isnt loaded correctly. Happened on my computer and on my friends. 
After reload everything is back to normal.
<img width="1260" alt="screen shot 2017-09-28 at 10 21 38" src="https://user-images.githubusercontent.com/7208102/31068412-2ec6d0c4-a758-11e7-9f83-dc83893eaa88.png">

**Comment by Gallore** [comment]
In this case only default machine profile is loaded but not MrBeamII profile.
Teja suggest to set the new MrBeamII as default.

**Comment by clemniem** [comment]
Got it again and with this error message in console: 
``
Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED) /plugin/mrbeam/profiles
``

**Comment by Gallore** [comment]
Is this only when the user isn't logged it while the page is opened/loaded?

**Comment by Gallore** [comment]
<img width="1379" alt="screenshot 2017-10-05 14 07 42" src="https://user-images.githubusercontent.com/4582388/31226500-96bb3ffa-a9d6-11e7-9c77-64bc5a8320b5.png">

**Comment by clemniem** [comment]
> Is this only when the user isn't logged it while the page is opened/loaded?

Hm.. maybe. But I think at least I was logged in when it happened. Or it stayed that way after log in at least.

**Comment by Gallore** [comment]
Call '''http://mrbeam-f930.local/plugin/mrbeam/profiles''' was protected by @restricted_access. Therefor an anonymous user (read: user is about to log in) didn't get machine profiles and therefor the working area was set back to default size (read: Mr Beam I size)
