### ISSUE TITLE
arrow keys error after limit hit

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#159]
If the arrow keys are pressed, the mr beam is moved.
if you move him to one end of the working area there is an unhandled error message due to the limit hit. For example:
- home mr beam
- press 3 times to the right 
--> lots of error messages.
They shouldnt pop up again and again. And the arrows probably shouldnt move the mr beam. 
Maybe shift+arrow: moves mr beam
arrow: moves design

**Comment by clemniem** [comment]
cant do homing until all error messages are clicked away! that is really annoying as well.

**Comment by Gallore** [comment]
We need to catch the limit hit before it happens.

**Comment by hungerpirat** [comment]
already fixed 2017.
