### ISSUE TITLE
Streamline Setup Wizzard

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#170]
- Check Reload / Reboot screens and texts
- Finish button at the end reacts ver slowly sometimes... (#51)
- #34 "SetupWizard: After wifi handover: Don't show same WizardWelcome page"
- test if this is still existing: #46 "Modal login dialog over setup wizard"
- #52 
- #38 "SetupWizard: wizard re-appears if user logs out and in again"
- ... (some testing)

**Comment by irlaec** [comment]
Fixed with the new welcome dialog
