### ISSUE TITLE
Remove 'cancel' button from conversion dialog until cancellation works

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#173]
Yep, you read correctly! Remove it!
See: #26 "Make conversion dialog cancelable"

**Comment by clemniem** [comment]
<img width="460" alt="screen shot 2017-10-23 at 18 48 08" src="https://user-images.githubusercontent.com/7208102/32383856-6ef2c39a-c0b9-11e7-8fea-9289800f8bac.png">
While at the jinja files. Remove those two options from conversion dialogue while converting,
