### ISSUE TITLE
never show undistorted picture

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#177]
if no good picture is created, show bad picture with information to frontend.

**Comment by clemniem** [comment]
If a BAD_QUALITY is perceived in the mb_pic_prep Plugin, there is no final image returned to save processing time. What should happen if only bad pictures are made? 
The Quickfix implemented above, just keeps showing the last good picture.

**Comment by hungerpirat** [comment]
related to #260

**Comment by amrsoll** [comment]
Other mechanism : Have more faith in the last known marker position
