### ISSUE TITLE
Conversion Dialogue: drag&drop of 'engrave' onto 'another job'

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#179]
Gives this erroneous result:
<img width="1253" alt="screen shot 2017-10-10 at 17 53 53" src="https://user-images.githubusercontent.com/7208102/31396591-12ef7e40-ade4-11e7-87e0-4c71aad5928a.png">

How to reproduce:
- put design on working area with picture
- drag and drop the engrave kitten onto 'drag here for another job'

**Comment by hungerpirat** [comment]
fixed.
