### ISSUE TITLE
When in Access Point Mode breath in different color

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/MrBeamPlugin#197]
LEDs should breath in a different color to show that the device is working in accesspoint mode.

Follow up question: Which color has the WiFi ?

**Comment by clemniem** [comment]
I just, wanted to write that same request! 
The MrBeam just booted in AP Mode and it took me like 5-10min to check everything before realising it is in AP mode...

WIFI: White ('normal', ready)
AP: MrBeam Orange (because you have to connect to MrBeam?)

**Comment by clemniem** [comment]
Idea:
Maybe we show some Hint in find.mr-beam.org? a la:
`If you cannot find your MrBeam check if its in AP Mode (look for color)`
