### ISSUE TITLE
mrbeam.py can't handle percentage in some svg attributes

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#20]
For debugging, this is the erroneous svg-file: 
`<svg width="250" height="200" xmlns="http://www.w3.org/2000/svg">
 
 <g>
  <title>background</title>
  <rect fill="#fff" id="canvas_background" height="202" width="252" y="-1" x="-1"/>
  <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid">
   <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%"/>
  </g>
 </g>
 <g>
  <title>Layer 1</title>
  <rect id="svg_1" height="102" width="122" y="22" x="33.5" stroke-width="1.5" stroke="#ff0000" fill="none"/>
  <rect id="svg_2" height="107" width="145" y="62" x="83.5" stroke-width="1.5" stroke="#0000ff" fill="none"/>
 </g>
</svg>`

Error:
  File "mrbeam.py", line 2907, in recursive_search
    w = float( i.get( 'width', '0' ) )
ValueError: invalid literal for float(): 100%

**Comment by make-ing** [comment]
I tested it on the NYMF version and its work properly.
