### ISSUE TITLE
Bug: Device remains in fan:auto mode after laser job forever

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#204]
Please make sure that the fan turns off once it isn't needed any more.
From what I remember, per design it runs for ~5 min in auto mode and turns off then. But the device next to me keeps annoying me with it's noise...

See end of log file....
[octoprint (4).log](https://github.com/mrbeam/MrBeamPlugin/files/1442294/octoprint.4.log)

**Comment by Gallore** [comment]
Same with the device we just used for the demo an hour ago.... ANNOYYYIIINGGG!!!!!

**Comment by Gallore** [comment]
Same in PAUSE mode. if the device remains paused, we should turn off the fan after some time.

**Comment by amrsoll** [comment]
fixed in #623

**Comment by amrsoll** [comment]
fixed in #623
