### ISSUE TITLE
Why is @firstrun_only_access disabled for rout '/calibration' etc?

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#208]
There are three instances where the `@firstrun_only_access` is disabled. From my understanding it's security relevant that this is enabled, isn't it @hungerpirat ?

__init__.py: line 653:
```
	@octoprint.plugin.BlueprintPlugin.route("/calibration", methods=["GET"])
	#@firstrun_only_access
	def calibration_wrapper(self):
```

__init__.py: line 698:
```
	@octoprint.plugin.BlueprintPlugin.route("/take_undistorted_picture", methods=["GET"])
	#@firstrun_only_access
	def takeUndistortedPictureForInitialCalibration(self):
```

__init__.py: line 706:
```
	@octoprint.plugin.BlueprintPlugin.route("/send_calibration_markers", methods=["POST"])
	#@firstrun_only_access
	def sendInitialCalibrationMarkers(self):
```

**Comment by clemniem** [comment]
Its disabled, so that without having someone logged in we can do some stuff from within OctoPrint, eg. the initial Camera Calibration. As far as I understood.

**Comment by Gallore** [comment]
@clemniem : Nope. It's designed to allow exactly this kind of access to OP. Without the annotation it's alway open to everyone. I just talked to Teja and he confirmed this assumption.

**Comment by Gallore** [comment]
`takeUndistortedPictureForInitialCalibration()` and `sendInitialCalibrationMarkers()` would need two decorators: `@firstrun_only_access` and `@restricted_access` but from my quick test just now, this combination doesn't work (at least not as expected).

**Comment by amrsoll** [comment]
@Gallore - This seems to relate to what we want to reinstate, with the extra spice when inserting a support key that bypasses the restriction
