### ISSUE TITLE
Time display (passed time) doesn't update during long running Gcode commands

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#218]
Looks like while a long running Gcode is performed, the backend keeps sending the same time to the frontend, so that the time counter there stops counting. Once the Gcode command has finished (and the next one gets processed) the time gets updated to the then correct value.

<img width="366" alt="screenshot 2017-11-13 18 01 48" src="https://user-images.githubusercontent.com/4582388/32738362-ec2de084-c89c-11e7-9086-3c5f6c6b986b.png">

Find SVG and GCO files attached:
[issue#218.zip](https://github.com/mrbeam/MrBeamPlugin/files/1467707/issue.218.zip)

**Comment by Gallore** [comment]
Maybe we simple handle time on the frontend. Just keep counting there...

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix "Laser Time" display](https://trello.com/c/Pwx8Y4Q4/68-fix-laser-time-display)
