### ISSUE TITLE
Working Area Blur effect issue: Designs with thin lines only disappear if they get blurred out

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#219]
Working Area Blur effect issue: Designs with thin lines only disappear if they get blurred out.

Both designs visible:
<img width="1510" alt="screenshot 2017-11-15 13 42 05" src="https://user-images.githubusercontent.com/4582388/32836640-cf9d5f3e-ca0a-11e7-90e5-01ae061363cb.png">

One design is blurred out because mouse hovers over the other one int the file list on the levt
<img width="1510" alt="screenshot 2017-11-15 13 41 57" src="https://user-images.githubusercontent.com/4582388/32836709-0be9f380-ca0b-11e7-9db5-9ffed8d646bc.png">

Use the file attached to reproduce:
[Lasercut_MOMA_01.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/1474701/Lasercut_MOMA_01.svg.zip)

**Comment by hungerpirat** [comment]
disabled blur effect some time ago.
