### ISSUE TITLE
Netconnectd logs are empty after some time

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#22]
On Raspberry Pi: Netconnectd logs are empty after one day. Once Nectconnectd got restarted, the log output is ok. But after the weekend, the log file has a size o zero bytes. I assume that the logrotate mechanism on our Raspberrys messes things up.

**Comment by make-ing** [comment]
fixed with commit: [29ca6a9](https://github.com/mrbeam/netconnectd_mrbeam/commit/29ca6a91fbcfddb5615d06afa9a5f3358cac310d)
