### ISSUE TITLE
Image: Permissions 0664 for '/root/.ssh/id_rsa' are too open.

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#220]
Please make sure that the permissions for this file are 600:
`sudo chmod 600 /root/.ssh/id_rsa`

octopi=production Mon Oct 23 09:55:38 UTC 2017

There's a chance that it was me who accidentally changed it on my device. But please double check anyway.

**Comment by make-ing** [comment]
should be fixed with new image build

**Comment by Gallore** [comment]
Verified: This is NOT in the image we shipped. (Sept 2017)
