### ISSUE TITLE
Setup Wizard needs to communicate how to use find.mr-beam.org

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#230]
From user feedback we learn that most users don't know about find.mr-beam.org
Find a way how to tell the user how to use find.mr-beam.org during setup wizard.

**Comment by amrsoll** [comment]
New Welcome dialog coming up 
https://github.com/mrbeam/MrBeamPlugin/tree/f_welcome_dialog_rework

**Comment by irlaec** [comment]
We recommend its usage in the new welcome dialog
