### ISSUE TITLE
Implement handling of SVG element 'switch'

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#233]
Read about the switch element: https://developer.mozilla.org/de/docs/Web/SVG/Element/switch

And here is a file that uses it: (came from Rubde):
[werkzeug_klein.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/1543535/werkzeug_klein.svg.zip)

**Comment by amrsoll** [comment]
See #643
