### ISSUE TITLE
832F: Only one interlock should OPEN when lid is open, but 2 should signal OPEN

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#234]
832F: Only one interlock should OPEN when lid is open, but 2 should signal OPEN

Steps to do:
- find out which interlock of the upper signals closed
- then find out why this is.

iobeam output:
```
pi@MrBeam-832F:~\> iobeam_info
iobeam:version:0.4.1
intlk:0:op
intlk:1:cl
intlk:2:cl
intlk:3:cl
steprun:off
lid:op
onebtn:up
unused:-
laser:temp:21.6
fan:version:2.3
fan:factor:0.35
fan:tpr:2
fan:pwm_min:55
fan:dust:0.26
fan:rpm:0
fan:state:0
fan:connected:unknown
```

**Comment by viktorijad** [comment]
Daniel sagt das die linke Interlock ist magnetisch uberpruckt.
