### ISSUE TITLE
Conversion dialog: hide engrave/cut settings if not available for the selected material

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#245]
Eg: Paper is selected I'm offered 'engraving only' even though there are no settings to engrave paper. (See screenshot). Don't show 'engraving only' option. Also in the Color Assignment section, remove the engraving part.

Similar: If Bamboo which can not be cut, all colors should be added to the engrave section by default. However it's useful if one is able to move colors from there to new jobs.

<img width="1438" alt="screenshot 2017-12-21 16 28 56" src="https://user-images.githubusercontent.com/4582388/34262488-cf6e4d7e-e66c-11e7-983b-1e3e1a312854.png">

**Comment by hungerpirat** [comment]
done
