### ISSUE TITLE
Conversion dialog: Prevent submission of conversion dialog if there a fields empty 

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#247]
If there are data fields empty it should not be possible to submit the conversion dialog. Currently it is even if there are not settings for engraving. 
Please also consider that the user might remove default values from material settings.

**Comment by hungerpirat** [comment]
For the case that some materials are either only engravable or cuttable, we have a
pragmatic solution. Unset job parameters are handled in the backend now. Colors assigned to jobs without complete parameters are skipped in the backend now.
