### ISSUE TITLE
Conversion Dialog: Reset button

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#253]
Conversion dialog should have a reset button that resets all values to the default ones.
Maybe we need to define what exactly 'default settings' means here. Still, from a user perspective, I want a way to go back to something that feel like a meaningful default after I played around like crazy.

**Comment by hungerpirat** [comment]
will come with merge of branch f_save_custom_material https://github.com/mrbeam/MrBeamPlugin/tree/f_save_custom_material

**Comment by hungerpirat** [comment]
already in production
