### ISSUE TITLE
Make conversion dialog cancelable

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#26]
Implement check-loop inside Converter.convert function if job_cancelled is set. see TODO in code.

**Comment by clemniem** [comment]
@make-ing @Gallore This is implemented already, isn't it?

**Comment by Gallore** [comment]
@clemniem 's notes:
- cancel request wird erst bei neuem Job wieder ausgefuehrt
- ich klick cancel und dann neben die convert leiste
- dann mach ich nen neuen job und klick auf convert
- auf einmal wird er abgebrochen, weil jetzt erst der request vom ersten cancel abgearbeitet wird
