### ISSUE TITLE
Working Area: Can not duplicate jpg/png grafics

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#261]
For any sort of pixel graphic, theres is no 'duplicate' button shown in the file list as it is for svg graphics. At least for consistency reasons, we need this functionality.

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Duplicate Design button for all](https://trello.com/c/fc8zIhis/80-2-duplicate-design-button-for-all)
