### ISSUE TITLE
SVG: this SVG file from vectr.com is not handled correctly

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#274]
[vertr_com_box.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/1847965/vertr_com_box.svg.zip)

The rectangle should have only an outline but no filling. On the working area it appears as a filling-only rectangle. File is created with online svg editor: https://vectr.com/

I assume that we don't support the `use`-tag in this SVG file.

**Comment by amrsoll** [comment]
Duplicate with #347
