### ISSUE TITLE
Bug: Laser stays off after pause; even in the beginning of a job

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#304]
Looks like G0 command are handled buggy by grbl.

Example 1:
Place a SVG file (e.g. MrBeam logo; not a QuickShape!) on working-area, start a laserjob. While the laserhead moves to it's first position, press pause, then unpause. Laser won't turn on when it should.
https://mr-beam.zendesk.com/agent/tickets/299

Romoved example 2 since it was NOT valid GCODE.

**Comment by hungerpirat** [comment]
In example 2, the gcode is clearly wrong. Good thing, I can't reproduce that anymore (Mr Beam Plugin: v0.1.17, OctoPrint: v1.3.6.2, Image fingerprint: None, Software tier: DEV, Environment: DEV)
Trying to reproduce example 1: no success (which is a good thing).

@Gallore are you able to reproduce that on some machine ?

**Comment by Gallore** [comment]
Never happened anymore!!!!!
