### ISSUE TITLE
Make sure, our GCode is always 100% ok

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#31]
Sometimes MrBeam just stops in the middle of a job, **LEAVING THE LASER ON!**
We really need to make sure, that this doesn't happen!

![bildschirmfoto 2017-02-24 um 14 16 34](https://cloud.githubusercontent.com/assets/4582388/23527218/5f95261c-ff95-11e6-9563-1a52b49d0e7c.png)

**Comment by hungerpirat** [comment]
the gcode is correct - the reason for invalid gcode ID 24 is streaming buffer related. 
Though we have a hardware safety circuit which turns the laser off, our grbl firmware should take care of that.

**Comment by Gallore** [comment]
duplicate of #116
