### ISSUE TITLE
SVG Problem: Filters element prevent engravings

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#312]
The filled areas (texts converted to paths) are not engraved. The `filter` elements in `defs`, which are referenced from almost every element in this file are preventing them from being processed and engraved correctly.

[SvenHaiges2.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/2232707/SvenHaiges2.svg.zip)

**Comment by hungerpirat** [comment]
![image](https://user-images.githubusercontent.com/3082129/72681798-6d9b0400-3ac7-11ea-91e0-8603e0afbdb7.png)
not able to reproduce anymore.
