### ISSUE TITLE
VERIFY: Uploading design file of same name does not update file in the browser.

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#313]
User Sven Haiges reported: https://mr-beam.freshdesk.com/a/tickets/726
> wenn ich die gleiche datei (gleicher Dateiname) erneut in den Beam hochlade, scheint es eine alte Version der Datei (cache?) zu benutzen. Das ist recht nervig, ich zaehle jetzt die Datei mit jeder Aenderung hoch... Ist das bekannt?

Need to be verified.

**Comment by Gallore** [comment]
Nachfrage
Ich habe einen Bugreport erstellt. Kannst du bitte noch folgendes probieren und mir berichten:
- Liegt dein Design bereits auf der Working Area, wenn du es hochlädst? Wenn ja probiere bitte, es von der Working Area zu entfernen und nach dem Upload neu hinzuzufügen.
- Wie verhält es sich, wenn du nach dem Upload die Seite im browser neu lädst? (F5 oder cmd+r)

Sven:
- auch wenn ich das File davor entferne, wird mir im design library und auch wenn ich das file dann auf den arbeitsbereich ziehe das falsche file angezeigt. Ich hab das file zweimal weggeloescht und dann einmal per drag & drop ins library und einmal per upload-button hochgeladen. 
- allerdings wird es korrekt angezeigt, wenn ich das file loesche, dann die website vom cutter neu lade und dann hochlade. ist wohl ne art caching problem...

**Comment by irlaec** [comment]
In my case:
- The preview of the file shows the previous image.
- When I place it on the working area, the new one is shown.
- The new image is lasered.
We could maybe check if the file name already exists in the design library, and if so add a counter to the new file, e.g: file_1.png. This way we would keep both files.

**Comment by irlaec** [comment]
#141

**Comment by amrsoll** [comment]
Closing because duplicate
