### ISSUE TITLE
SVG Issue: paths (looking like circles) turn into flat lines in GCODE

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#319]
This SVG file (coming from a DXF file from Basti) contains circles that get converted into lines in GCODE.

This circle:
<img width="84" alt="screenshot 2018-08-13 16 09 51" src="https://user-images.githubusercontent.com/4582388/44036962-720dd25c-9f13-11e8-8eca-aad3cf290e9f.png">

tuns into this flat line:
<img width="71" alt="screenshot 2018-08-13 16 09 28" src="https://user-images.githubusercontent.com/4582388/44036966-74f8fc9e-9f13-11e8-8dfc-5417fa8cbee2.png">

![box](https://user-images.githubusercontent.com/4582388/44036881-2d267fd6-9f13-11e8-90cf-67da5758e99e.png)

Find SVG and GCODE in this ZIP file:
[Box.zip](https://github.com/mrbeam/MrBeamPlugin/files/2283231/Box.zip)

**Comment by hungerpirat** [comment]
fixed by commit bd7b20b
