### ISSUE TITLE
Update content of LaserSafty Notice Dialog

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#32]
This dialog still addresses the first MrBeam. (it's still talking about device assembly...)

This to include there:
- Tell the user the we'll send this data to the MrBeam Cloud. Tell them that the Show Again checkbox works only if MrBeam has internet connection.
-

**Comment by Gallore** [comment]
There are two jinja files:
octoprint_mrbeam/templates/lasersafety_standalone.jinja2
octoprint_mrbeam/templates/wizard/wizard_lasersafety.jinja2
both include this file which is the main one to edit:
octoprint_mrbeam/templates/lasersafety_genericbody.jinja2

**Comment by hungerpirat** [comment]
Wondering if the dialog content should be machine-specific @Gallore ?

**Comment by Gallore** [comment]
done
