### ISSUE TITLE
Show Mac address in settings

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#329]
Some users need to know the mac address of their Mr Beam to configure firewalls and stuff. Especially schools and universities.

We should show the mac address (eth0 and wlan0) in mr beam settings.

https://mr-beam.freshdesk.com/a/tickets/914

**Comment by hungerpirat** [comment]
![image](https://user-images.githubusercontent.com/3082129/73608442-3c402f00-45c3-11ea-89e1-983402f2bfdb.png)
