### ISSUE TITLE
SVG: Image proportions do not match globally and within the image

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#354]
SVG: Image proportions do not match globally and within the image

The file is from: https://www.instructables.com/id/Laser-Cut-Geometric-Pencil-Holder/

![screenshot 2018-11-22 15 01 34](https://user-images.githubusercontent.com/4582388/48909296-2b4b4800-ee6d-11e8-8bea-dcbe96401570.png)

Find all files (SVG, GCO, Screenshots) here:
[ticket#354.zip](https://github.com/mrbeam/MrBeamPlugin/files/2608478/ticket.354.zip)

**Comment by hungerpirat** [comment]
there is css code inside the svg hiding a complete layer with "display:none" .
The hidden layer contains the larger overlaying paths.
