### ISSUE TITLE
Username must be called "E-mail address" everywhere.

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#36]
In OctoPrint login is username + pw. We changed it to E-Mail address and pw. We should name it "E-mail address" consistently.

Here is an INCOMPLETE list of locations where we need to change the label:
- Settings, where admins can create new user accounts

**Comment by Gallore** [comment]
see also #37

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Username in Access Control in settings](https://trello.com/c/5dtPqqaT/111-username-in-access-control-in-settings)
