### ISSUE TITLE
SVG: Order of the cuts seems arbitrary and sub-ideal

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#366]
Let's see if there's a better way to handle this. 
All lines are separate groups with one path inside. However the original order of the groups would be good as cutting order.

[test_ticket_366.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/2676615/test_ticket_366.svg.zip)

**Comment by Gallore** [comment]
Even after breaking all the groups and then joining the plain paths into one path (per shape), the order is better but still not ideal. looks like the internal order within the path is unsorted.

**Comment by hungerpirat** [comment]
separated images are sorted with fefe06d . Paths should be sorted here: https://github.com/mrbeam/MrBeamPlugin/blob/develop/octoprint_mrbeam/gcodegenerator/converter.py#L348
