### ISSUE TITLE
Duplicate objects on working area not available for bitmap grafics (jpg, png..), QuickText nor QuickShapes

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#367]
Duplicate objects on working area not available for bitmap grafics (jpg, png..), QuickText nor QuickShapes.

Should be available for all types of objects.

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Duplicate Design button for all](https://trello.com/c/fc8zIhis/80-2-duplicate-design-button-for-all)

**Comment by irlaec** [comment]
(partially) duplicated: #261
