### ISSUE TITLE
Normalize username/e-mail address (Email addresses are NOT case sensitive, but OP username is)

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#37]
Normalize username/e-mail address (Email addresses are NOT case sensitive, but OP username is)
Andy@Mr-Beam.org == andy@mr-beam.org

Currently OctoPrint's username IS case sensitive which might be confusing.

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Login: make email addresses not case sensitive](https://trello.com/c/8M1meUEQ/76-login-make-email-addresses-not-case-sensitive)
