### ISSUE TITLE
SetupWizard: wizard re-appears if user logs out and in again

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#38]
SetupWizard: wizard re-appears if user logs out and in again:

I see two possible solutions to this: 

- Force the frontend to reload after the wizard has been finished. Theoretically if one vewmodel returns 'reload' in the onWizardFinish() callback (http://docs.octoprint.org/en/master/plugins/viewmodels.html#callbacks), the frontend should get reloaded. Did work for me, but I didn't debug much.

- Once the wizard is finished, the frontend sends a call to the backend '/api/setup/wizard' which has a list of wizards (plugins?) as body. Currently this list is empty for whatever reason. I'm not sure if we need to include 'corewizard' or 'mrbeam' or bith in this list. And neither am I sure that this would solve the initial issue. But we might investigate here.
```{"handled":["corewizard"]}```

**Comment by irlaec** [comment]
Fixed
