### ISSUE TITLE
MrBeam Job World Map is place too low on a Mac screen

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#395]
MrBeam Job World Map is place too low on a Mac screen

<img width="1509" alt="screenshot 2019-02-13 13 48 08" src="https://user-images.githubusercontent.com/4582388/52712848-2098de80-2f96-11e9-88ef-0d87b072800d.png">

**Comment by irlaec** [comment]
The map is removed now (#493), commit 08db16cfff219900365f7ee649007dd583f7f73b
