### ISSUE TITLE
Real time image adjustments sliders in the working area

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#401]
teja implemented the prototype on the weekend. Now bring this into development by following the TODOs further down.

* branch: f_realtime_img_adjust
* TODOs:
    * remove switches from conversion dialog
    * limit to 90% and/or maybe change contrast slider to increase-option only
    * re-enable quick text font copying
        * test if copying the font defs into the svg even though no quick text is used brings a relevant speed up
    * end-to-end test
    * add sharpening slider
    * try gamma-correction slider
    * clean up backend (remove unneeded code)
    * end-to-end test
* Links:
    * https://www.html5rocks.com/en/tutorials/canvas/imagefilters/

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Image adjustment integrated in develop](https://trello.com/c/IVrj1Ylr/36-3-image-adjustment-integrated-in-develop)

**Comment by irlaec** [comment]
#442
