### ISSUE TITLE
Integrate DXF import plugin from Nick

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/MrBeamPlugin#43]
Steps to do: 

- ~~fork the plugin~~ This is the fork: https://github.com/mrbeam/snap-dxf
- integrate js
https://github.com/mrbeam/MrBeamPlugin/blob/master/octoprint_mrbeam/__init__.py#L101

- enable file type dxf
https://github.com/mrbeam/MrBeamPlugin/blob/8c159d3006cf6ff9c21ec47dac50fcb1790dc8dd/octoprint_mrbeam/__init__.py#L613

- knockout view template for dxf (if necessary)
https://github.com/mrbeam/MrBeamPlugin/blob/8c159d3006cf6ff9c21ec47dac50fcb1790dc8dd/octoprint_mrbeam/static/js/working_area.js#L616

- implement placeDXF() function analog to placeSVG() in working_area.js

**Comment by Gallore** [comment]
Get a DXF file from thingiverse.com (search for lasercut)

**Comment by hungerpirat** [comment]
DXF support integrated.
