### ISSUE TITLE
Can't use dithering with black&white vector file, result is all black

### ISSUE THREAD

**Issue by irlaec** [mrbeam/MrBeamPlugin#455]
Reported by Oli Bischoff:

When trying to laser any black and white vector file with dithering, the result is an all black image.

I reproduced it with [this SVG](https://game-icons.net/1x1/delapouite/school-of-fish.html)

**Comment by hungerpirat** [comment]
I tested and reproduced it. switching engraving mode to 'basic' is a workaround. Looks like dithering and separation of images are somehow interfering.

**Comment by hungerpirat** [comment]
fixed by fde7aa4
