### ISSUE TITLE
Pixel graphic gradually vanishes when zooming in the working area

### ISSUE THREAD

**Issue by irlaec** [mrbeam/MrBeamPlugin#543]
If there is a pixel graphic (png, jgp) in the working area and you zoom in, the design starts disappearing from the bottom: 
![image](https://user-images.githubusercontent.com/28774305/61710066-fae7e080-ad50-11e9-8aae-3e620fc946e8.png)
With svg and dxf files everything looks right.

**Comment by hungerpirat** [comment]
should be fixed commit fd55eb8
