### ISSUE TITLE
The pierce time only shows for the first cutting job

### ISSUE THREAD

**Issue by irlaec** [mrbeam/MrBeamPlugin#607]
When there is a job with more than a cutting job and you show the advanced options, the pierce time is only shown for the first cutting job, not for the second one.

**Comment by hungerpirat** [comment]
![image](https://user-images.githubusercontent.com/3082129/72681520-b8674c80-3ac4-11ea-8259-d1454ac0b57a.png)

can't reproduce in current develop (see screenshot). Looks fine, works fine...
