### ISSUE TITLE
Laser params tooltip: Add min & max values for feedrate to tool tip text

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#637]

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Laser params tooltip: Add min & max values for feedrate to tool tip text #637](https://trello.com/c/McsdtsrE/606-laser-params-tooltip-add-min-max-values-for-feedrate-to-tool-tip-text-637)
