### ISSUE TITLE
Marker notification tooltips need improvement

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#703]
When the pink markers on the working area show, it is not clear wha this is. A tooltip would be useful. Current SVG tooltip takes too long to show (user doesn't expect to wait) and do not look nice.

Here is a tutorial on how to create tooltips in SVGs:
https://codepen.io/billdwhite/pen/rgEbc

**Comment by amrsoll** [comment]
New messages added in the Preview tab which shows when hovering over the pink circles.
