### ISSUE TITLE
Job time estimation should be shown while lid is open but does not

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#761]
Does not show here:

<img width="580" alt="Screenshot 2020-03-06 at 14 28 38" src="https://user-images.githubusercontent.com/4582388/76087655-e6dab180-5fb6-11ea-8ad2-d1ac4892c37c.png">

should be show like here:
<img width="576" alt="Screenshot 2020-03-06 at 14 28 46" src="https://user-images.githubusercontent.com/4582388/76087674-f0fcb000-5fb6-11ea-82c5-01daed450552.png">

**Comment by irlaec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Job time estimation should be shown while lid is open but does not #761](https://trello.com/c/RBOjwD0t/605-job-time-estimation-should-be-shown-while-lid-is-open-but-does-not-761)
