### ISSUE TITLE
Using a code formatter for GitHub actions.

### ISSUE THREAD

**Issue by amrsoll** [mrbeam/MrBeamPlugin#822]
The idea is that we won't have to bother telling each other how we prefer to format the code. [Black](https://github.com/psf/black) is a code formater that adheres as much as possible to the PEP 8 guidelines and can be added on our editors as a plugin as well as a commit checker on the github side.

However, this means that we would have to move back to using spaces for indentation. Perhaps an other formater would give us the flexibility.

**Comment by irlaec** [comment]
This is already in place (after v0.7.5)
