### ISSUE TITLE
BeamOS image: preinstall OpenCV for camera calibration and image correction

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#83]
OpenCV for Pi:
https://github.com/jabelone/OpenCV-for-Pi

From my experience: we need all packages from this tutorial, even the ones for video.

Make it available in venv:
cp /usr/local/lib/python2.7/dist-packages/cv2.so ~/oprint/local/lib/python2.7/site-packages/

**Comment by make-ing** [comment]
integration done but testing pending:
https://bitbucket.org/mrbeam/octopi/commits/da9ff094136467f0aec4f859fb1b93fade890362
