### ISSUE TITLE
BeamOS image: preinstall usb_mount_manager

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#84]
https://bitbucket.org/mrbeam/usb_mount_manager/overview

**Comment by make-ing** [comment]
integration done testing needed:
https://bitbucket.org/mrbeam/octopi/commits/408bd12a09e224793a4839b5e9f0c16241ab4106

**Comment by make-ing** [comment]
fixed wrong installation dir:
https://bitbucket.org/mrbeam/octopi/commits/fc0f930deddf83394ef52d5e85a45cc38ad4317b
