### ISSUE TITLE
beamOS Image: let pip access private Bitbucket repos per ssh and as su

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#87]
Prepare beamOS image so that we can update ioBeam and other software from private Bitbucket repos. 

`rm /root/bin/git`
(Otherwise git won't run per sudo)

For users pi and root (Yes!!! for both users):
- create folder .ssh
- add private deployment ssh key (private key only!). Find the key in KeePassX and make it accessible only to the user himself (-rw-------)
- put known_hosts file there which has to contain Bitbucket server to avoid RSA key fingerprint question during update. (File attached) 
[known_hosts.zip](https://github.com/mrbeam/MrBeamPlugin/files/1047769/known_hosts.zip)
- make sure the public key is added to the project's "Access Keys" (aka deployment keys) on Bitbucket. (Already done for iobeam)
- change pip url for iobeam in software_update_information.py to: `pip="git+ssh://git@bitbucket.org/mrbeam/iobeam.git@{target_version}",`

**Comment by make-ing** [comment]
https://bitbucket.org/mrbeam/octopi/commits/68d2e8bb300e30fa29dbc93acba6b1ad931094a5
