### ISSUE TITLE
Preview tab unfolds when hovering over invisible pink markers

### ISSUE THREAD

**Issue by amrsoll** [mrbeam/MrBeamPlugin#967]
When hovering the mouse in one of the corners, the Preview tab unfolds even if the marker were detected and is not visible in the work area.

**Comment by Gallore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug](https://trello.com/c/lQgiMX7m/627-bug)

**Comment by amrsoll** [comment]
Only happens when markers were previously not found (not an issue when you refresh the page again)
